Repeat of commit f808eee for interop tests
Trying to fix:

+ cd grpc
+ tools/jenkins/run_interop.sh
++ dirname tools/jenkins/run_interop.sh
+ cd tools/jenkins/../..
+ tools/run_tests/run_interop_tests.py -l all -s all --cloud_to_prod \
  —cloud_to_prod_auth --use_docker --http2_interop -t -j 12
START: Building interop docker images.
START: build_docker_php7
Traceback (most recent call last):
  File "tools/run_tests/run_interop_tests.py", line 738, in <module>
    build_jobs, newline_on_success=True, maxjobs=args.jobs)
  File "tools/run_tests/jobset.py", line 456, in run
    if not js.start(cmdline):
  File "tools/run_tests/jobset.py", line 369, in start
    self._add_env)
  File "tools/run_tests/jobset.py", line 218, in __init__
    self.start()
  File "tools/run_tests/jobset.py", line 228, in start
    env = sanitized_environment(env)
  File "tools/run_tests/jobset.py", line 53, in sanitized_environment
    sanitized[str(key).encode()] = str(value).encode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 20:
ordinal not in range(128)