specify -stdlib=libc++ for darwin
It's not the default with older Apple clang builds
and without it c++11 features don't work on at least OS X 10.7:

 ./src/core/lib/gprpp/ref_counted.h:28:10: fatal error: 'atomic' file not found
 #include <atomic>
          ^~~~~~~~

I manually tested it on macOS 10.11 image and there was not a
regression.

This should fix the "Artifact Build MacOS (internal CI)" test failure.